### ISSUE TITLE
Can't find 'replace' of undefined 

### ISSUE THREAD

**Issue by osayfun** [mcollina/mqemitter-redis#19]
I'm getting this error when I'm running my project

`
TypeError: Cannot read property 'replace' of undefined
    at new MQEmitterRedis (/home/ubuntu/mqtt/node_modules/mqemitter-redis/mqemitter-redis.js:70:67)
    at MQEmitterRedis (/home/ubuntu/mqtt/node_modules/mqemitter-redis/mqemitter-redis.js:14:12)
`

My code works on MacOs and node version 12.12.0 but doesn't on server Ubuntu 18.04 and node 12.16.1

**Comment by mcollina** [comment]
Can you upload an example to reproduce?
Il 19 feb 2020, 01:05 -0700, Omid Seyfan <notifications@github.com>, ha scritto:

**Comment by osayfun** [comment]
I'm using MQEmitter v4.1.0 and MQEmitter-redis v4.0.0
`
var redis = require("mqemitter-redis");
var mq = redis({
  port: 6379,
  host: "127.0.0.1",
  db: 0
});
const aedesPersistenceRedis = require("aedes-persistence-redis");
const persistence = aedesPersistenceRedis({
  port: 6379,
  host: "127.0.0.1",
  family: 4,
  db: 0
});

const aedes = require("aedes")({
  persistence,
  mq
});
const server = require("net").createServer(aedes.handle);
const port = 1883;

server.listen(port, function() {
  console.log("server started and listening on port ", port);
});

`

**Comment by mcollina** [comment]
Released mqemitter@4.1.1 that should solve this
