### ISSUE TITLE
How to properly close connection?

### ISSUE THREAD

**Issue by mhf-ir** [mcollina/mqemitter-redis#38]
```
  /**
   * @returns {Promise<void>}
   */
  async quit() {
    if (this.mQEmitter) {
      await new Promise((resolve) => {
        this.mQEmitter.close(() => {
          resolve();
        });
      });
      this.mQEmitter = undefined;
    }
  }
```

Seems be it's not call.
![Screenshot from 2021-02-23 20-20-58](https://user-images.githubusercontent.com/1172526/108877681-b7341780-7614-11eb-8ffc-130f59a41978.png)

```

Jest has detected the following 1 open handle potentially keeping Jest from exiting:

  ●  RANDOMBYTESREQUEST

      at nodeRNG (node_modules/uuid/lib/rng.js:7:17)
      at v4 (node_modules/uuid/v4.js:13:52)
      at hyperid (node_modules/hyperid/hyperid.js:19:19)
      at Object.<anonymous> (node_modules/mqemitter-redis/mqemitter-redis.js:5:35)
```

**Comment by mhf-ir** [comment]
Seems be connection is not running during test. For testing purpose how to await for connection is ready and connected?
New connection is not ready and we need for wait for connection is ready then application continue

**Comment by mcollina** [comment]
It looks like this is some false positive in `jest`. hyperid works as expected.
