### ISSUE TITLE
How to disable LRU cache?

### ISSUE THREAD

**Issue by syberkitten** [mcollina/mqemitter-redis#4]
Trying to use the aedes-redis-persistence with the mqemitter-redis
I noticed the mqemitter-redis uses an LRU cache.

Does this mean that cached topics will never be written to Redis and therefore
will never be replicated nor persisted?

Or the cache is used only for outgoing packets that have already been sent?
Thus reducing the cost of traversing to the Redis instance?

these are the lines:
https://github.com/mcollina/mqemitter-redis/blob/master/mqemitter-redis.js#L24-L27

**Comment by mcollina** [comment]
The LRU cache is used to deduplicate messages if you have multiple overlapping subscriptions in Redis.
At the moment, you cannot disable the cache as it's needed to fullfil the mqemitter contract.
