### ISSUE TITLE
Replace `shortid` via `hyperid` for performance reasons?

### ISSUE THREAD

**Issue by behrad** [mcollina/mqemitter-redis#7]
https://github.com/mcollina/mqemitter-redis/blob/da684f3b6690268c9e5aeb3f795690b829498243/mqemitter-redis.js#L133

**Comment by mcollina** [comment]
definitely! PR?

**Comment by behrad** [comment]
> PR?

sure 👍

**Comment by kibertoad** [comment]
This can be closed now that https://github.com/mcollina/mqemitter-redis/pull/11 was merged
